# Generated by Django 3.2 on 2021-05-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Ферма', max_length=100, verbose_name='Название')),
                ('token', models.CharField(max_length=200, unique=True, verbose_name='Токен')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_public', models.BooleanField(blank=True, default=False, verbose_name='Публичный доступ')),
            ],
            options={
                'verbose_name': 'Ферма',
                'verbose_name_plural': 'Фермы',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('light_on_time', models.TimeField(blank=True, null=True, verbose_name='Включение света')),
                ('light_off_time', models.TimeField(blank=True, null=True, verbose_name='Выключение света')),
                ('solution1', models.PositiveIntegerField(blank=True, default=0, verbose_name='Раствор1')),
                ('solution2', models.PositiveIntegerField(blank=True, default=0, verbose_name='Раствор2')),
                ('solution3', models.PositiveIntegerField(blank=True, default=0, verbose_name='Раствор3')),
                ('co2', models.PositiveIntegerField(blank=True, default=0, verbose_name='CO2')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.farm', verbose_name='Ферма')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(verbose_name='Дата записи')),
                ('ph', models.FloatField(blank=True, null=True, verbose_name='PH')),
                ('tds', models.FloatField(blank=True, null=True, verbose_name='TDS')),
                ('air_temp', models.FloatField(blank=True, null=True, verbose_name='Температура воздуха')),
                ('humidity', models.FloatField(blank=True, null=True, verbose_name='Влажность воздуха')),
                ('water_temp', models.FloatField(blank=True, null=True, verbose_name='Температура раствора')),
                ('co2', models.FloatField(blank=True, null=True, verbose_name='CO2')),
                ('max_level', models.BooleanField(blank=True, null=True, verbose_name='Максимальный уровень раствора')),
                ('min_level', models.BooleanField(blank=True, null=True, verbose_name='Минимальный уровень раствора')),
                ('sensors_tank_level', models.BooleanField(blank=True, null=True, verbose_name='Минимальный уровень бака для датчиков')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.farm', verbose_name='Ферма')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
