# Generated by Django 3.2 on 2021-05-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0002_farm_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание'},
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameters', models.JSONField(verbose_name='Параметры')),
                ('record_date', models.DateTimeField(verbose_name='Дата записи')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.farm', verbose_name='Ферма')),
            ],
            options={
                'verbose_name': 'Параметры',
                'verbose_name_plural': 'Параметры',
            },
        ),
    ]
