# Generated by Django 3.2 on 2021-05-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0003_auto_20210508_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
    ]
