# Generated by Django 3.2 on 2021-12-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farms', '0007_auto_20210518_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='co2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='CO2'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='solution1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Раствор1'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='solution2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Раствор2'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='solution3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Раствор3'),
        ),
    ]
